@startuml sub-activation-bonus

start
:Le joueur clique sur un bonus dans l'inventaire;
switch (Type de bonus)
  case (Temps ralenti)
    :Activer ralentissement du temps;
    :Durée : 3 secondes;
  case (Temps accéléré)
    :Activer accélération du temps;
    :Durée : 3 secondes;
endswitch
stop

@enduml
