name: "ci"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, staging, main]

jobs:
  lint-commit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.2"
      - uses: "wagoid/commitlint-github-action@v6.1.2"

  lint-editorconfig-checker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.2"
      - uses: "editorconfig-checker/action-editorconfig-checker@main"
      - run: "editorconfig-checker"
